### ISSUE TITLE
Health & Safety management system documentation

### ISSUE THREAD

**Issue by michaellihai** [OCA/management-system#132]
Has anyone written a detailed user guide that explains how to use all the functions in the Health & Safety Management System module?

module: mgmtsystem_health_safety
version: 8.0

**Comment by max3903** [comment]
Hello Michael,

I haven't heard of such documentation except the one in the module descriptions. I made some presentations about the use of actions, nonconformities, audits, etc but not specifically related to the H&S MS. The H&S modules are inspired from the ISOsystemplus free trial that I was able to evaluate couple years ago. Not much time has been spent on those modules mostly due to the lack of interest and funding, but the basis is there.

Please be aware that the OHSAS 18001 standard will soon be replaced by ISO 45001, as explained in #128.

If you have questions, resources or some love for those modules, please do not hesitate to ask and I will do my best to help you.

**Comment by dreispt** [comment]
AFAICS no further action needed on this.
