### ISSUE TITLE
Odoo V10 MRP/PLM and Management System

### ISSUE THREAD

**Issue by djsftree** [OCA/management-system#155]
Hi,

I've been reviewing the video at https://www.youtube.com/watch?v=9Glhyc9NffM regarding the new MRP/PLM and Quality system coming in V10.

How will the OCA Management System integrate with that do you think?  Will they be complimentary?

**Comment by dreispt** [comment]
Conceptualy, Management Systems and (Operational) Quality Control are different but complementary areas. 
I would say that they can be integrated, but it depends on what feature will be available on Community edition. 
Personally, my expectations are that, unless stated otherwise, all new features are on the Enterprise eduition only.
