### ISSUE TITLE
[RFC] Management System extension for production

### ISSUE THREAD

**Issue by mymage** [OCA/management-system#263]
To continue the discussion started on the mailing list Contributors [https://odoo-community.org/groups/contributors-15/contributors-144648?mode=date&date_begin=2019-09-01&date_end=2019-10-01](https://odoo-community.org/groups/contributors-15/contributors-144648?mode=date&date_begin=2019-09-01&date_end=2019-10-01), we propose a module to add some features to fit some manufacturing needs.

Identification of the Department, the Workcenter and the Product of the NC, record of the quantity checked and not compliant, Partner reference for quality communications, Actions templates and efficacy indication.

You can find the module here 
[https://gitlab.com/PNLUG/Odoo/management-system-improvements/tree/11.0/mgmtsystem_extended](https://gitlab.com/PNLUG/Odoo/management-system-improvements/tree/11.0/mgmtsystem_extended)

These Issued is connected to the [OCA/manufacture#425](https://github.com/OCA/manufacture/issues/425) Issue for the Manufacture repository.

Please give us your opinion, our purpose is to incorporate it in the OCA repository.

At the moment the module is for the 11.0 version.

**Comment by max3903** [comment]
Hello @mymage,

Thanks for the contributions and welcome to the OCA!

This looks like a big module with a lot of features and dependencies. To include it in the OCA and have a higher chance of adoption, we would need to make sure people can use only the features they need. We usually achieve this with one feature = one module, but we can also have one module with one setting per feature.

I don't know how much effort you want to put into this but here are couple options:
1. contribute your module as is and as a beta module. Make sure the CI (Travis and Runbot) are green
2. split your module and push one module at a time. As a beta (no unit tests) or stable (with unit tests) one.

You can also mix those options with the Odoo version, for example: use option 1 on version 11 and option 2 on version 12.

**Comment by mymage** [comment]
@max3903 Thanks for the first suggestions. I think that for this module is better to ad the configuration option so I will work in that direction. In the mean time I will try it on runbot and for this I have to do a PR (right?): there are some specific things to follow to open a "test" PR?

**Comment by ivantodorovich** [comment]
Hi @mymage !

This is very interesting :) Thanks !!

I think some of the features could be improvements done directly on the current modules.
For instance:

- Immediate Actions: replace the reference of a single Immediate action with one to multiple Immediate Actions

That's something I also thought about improving a while ago, and IMO this should be commited directly into mgmtsystem_nonconformity (with proper migration script!).

---

<dl>
  <dt>Type: add a field to classify a NC in Internal, Partner, Customer, External.</dt>
  <dd>Internal: when the NC is due and revealed in an internal process Partner: when the NC is due to a Partner Customer: when the NC si due and connected to a claim of the Customer External: when the NC si due and connected to a claim of an External entity (e.g. an Authority)</dd>
</dl>

That's also interesting aswell.. and as long as it remains optional (required=False), it wouldn't harm other users if we add it in the current module.

One thing though, in your repository this is a selection field. Maybe you could change that to a Many2one field (exactly how origin, cause, severity are managed)

That makes it easier configure the types, if needed.


---

On the other hand, these two :

* Department: add a field for link a specific department.
* Workcenter: add a field for link a specific workcenter.

These features would require depending on other modules like `hr` or `mrp`.
So it's better to keep them in separate modules.

Maybe they could be auto-installable modules, so they install automatically if the user is already using `hr` or `mrp`.

But in the case of workcenters, also check the user groups to know if he is using the workcenters, and only show the field if he is.

**Comment by max3903** [comment]
@mymage 

> In the mean time I will try it on runbot and for this I have to do a PR (right?)

Yes!

> there are some specific things to follow to open a "test" PR?

Just start the title with WIP:

**Comment by mymage** [comment]
@max3903 @ivantodorovich Following your suggestions I create the PR #264.
It is an initial version, I will notify you when ready to check.

**Comment by mymage** [comment]
> These features would require depending on other modules like `hr` or `mrp`.
> So it's better to keep them in separate modules.

I separated the two modules and Product too.
Other changes will come soon ;-)

**Comment by mymage** [comment]
@ivantodorovich 
> Type: add a field to classify a NC in Internal, Partner, Customer, External.
> That's also interesting aswell.. and as long as it remains optional (required=False), it wouldn't harm other users if we add it in the current module.
> One thing though, in your repository this is a selection field. Maybe you could change that to a Many2one field (exactly how origin, cause, severity are managed)
> That makes it easier configure the types, if needed.

I'm not sure this is a good idea. As far I know of the quality systems in manufacture there are three types of NC: Internal, Partner, Customer. Each of them has different "consequences". 
For example, we set a button to send the NC via email to the partner but these is useful only for Partner-Type NC. An extension for Customer-Type will be the creation of an 8D module.
We just add the External-Type to manage the case in which an Authority generate an NC because these is a new player.
So I prefer to keep a "rigid" structure to associate some automations.

**Comment by mymage** [comment]
@max3903 @ivantodorovich Hi, I removed the reference to immediate actions (which I will present with another PR on the basic module), if something does not escape me, now everything should be right.

**Comment by mymage** [comment]
@max3903 @ivantodorovich Hi, after talking with some italian's OCA members, it has point out that it will be better to split the main PR #264 in other two (as @max3903 suggested from the begin), one for the Actions e one for the NC and thus change the name of the modules in something more explicit than "extension". In the next days we will analyze the options and in case we will reorganize the PRs.

**Comment by mymage** [comment]
@max3903 Hi, I think that now the original module is well "exploded" on 7 PRs. 
There is a problem with #282 on runbot that I don't understand.
