### ISSUE TITLE
[V12] Error when saving procedures o work instructions

### ISSUE THREAD

**Issue by FranciscoBigWings** [OCA/management-system#353]
Hello, 

When trying to save those documents I get a restriction error from mail module. 

"La operación no se puede completar: otro modelo necesita el registro que está siendo eliminado. Si es posible, archívelo en su lugar.
Modelo: Message (mail.message), Restricción: mail_message_parent_id_fkey"

Management system modules has been installed from first time in this Odoo V12, they havent been migrated, so this is the first time using them. No procedure or work instruction documents has ever been saved before

**Comment by FranciscoBigWings** [comment]
The "Procedures" and "Work instructions" can be created from the "Manuals" tab

In category field, choosing the one I want, it creates the documents. After you can edit and save the document without any problem from the procedures or work instructions menu but from those menus it is not possible to create the document

**Comment by rizzopablo** [comment]
Same here, I didn't debug it yet but I have the same problem.

**Comment by jaenbox** [comment]
Apologies for my English.

**It is a bug that has not been fixed in several versions. mail_messages are being associated with a parent_id that is not correct.**

The problem is caused in the definition of the action of the procedure window, work instructions, etc ...

By including default_partner_id as context in window action. When saving document.page and creating the mail_message object it assigns the id of the record document_page_procedure.document_page_group_procedure in my case 9 as parent_id of the mail_message object.
As there is no mail_message with this id, for that reason it indicates the error:
"The operation cannot be completed: another model needs the record being deleted. If possible, file it instead. Model: Message (mail.message), Constraint: mail_message_parent_id_fkey"

I attach some screenshots so you can check it.

The id to the reference in my database to this record document_page_procedure.document_page_group_procedure is 9

![imagen](https://user-images.githubusercontent.com/16722317/146569820-3be55574-0994-4216-befe-749c45337b12.png)

I have deleted my record 9 from mail_message
![imagen](https://user-images.githubusercontent.com/16722317/146570019-33be8773-dc14-4f3c-812e-53d063ebc3c7.png)

When trying to save a document.page
![imagen](https://user-images.githubusercontent.com/16722317/146570103-9678210a-58ab-4f5d-8f65-30ede67b2319.png)


The solution:
Create an inherited view that overrides the window action and does not pass this parameter to it as context or includes another.
``
    <record model="ir.actions.act_window" id="document_page_procedure.action_procedures">
        <field name="name">Procedures</field>
        <field name="res_model">document.page</field>
        <field name="view_mode">tree,form</field>
        <field name="help">Procedures of your management system.</field>
        <field name="domain" eval="[('parent_id','=',ref('document_page_procedure.document_page_group_procedure'))]"/>
        <field name="context" eval="{'document_page_id': ref('document_page_procedure.document_page_group_procedure')}"/>
    </record>
``
Include in _default_category function

``
class DocumentPage(models.Model):
    _inherit = "document.page"

    def _default_category(self):
        if self.env.context.get('document_page_id'):
            return self.env.context.get('document_page_id')
        else:
            return False

    parent_id = fields.Many2one(
        'document.page',
        'Category',
        domain=[('type', '=', 'category')],
        default=_default_category)
``

I hope I could have helped
