### ISSUE TITLE
Improvement on detection of Procedures

### ISSUE THREAD

**Issue by etobella** [OCA/management-system#518]
Right now, the only way to detect procedures is to use a single category created as data. It is a problem when the environment is complex, as a simple category for all your procedures might be hard to manage.

I have two ideas for that:

1- Adding them as `type`of document.page (some changes might be necessary, but not too much)
2- Create a subtype

Obviously, some migrations scripts are necessary, but I might be able to do that :smile: 

This could be used for procedures, work instructions, quality manuals...

@max3903 WDYT?

**Comment by max3903** [comment]
@etobella I would go with the following options:

3- Use tags

:)

**Comment by diggy128** [comment]
I think that adding tags is a complexity not needed, however complex the documentation may be.

Defining the type of document with many2many tags is error prone and can result to eg. A Procedure having both a procedure a and a work instruction tag set.

In our organization we use a clear tree structure for documents. Procedure is a root document category and it can have documents or/and child categories which themselves are procedures (per sector or function).
This gives a clean outline of the categories in the content of each category (customized to serve as a document index for ISO 9001 and ISO 22000).

Finally adding a dependency in the base module would not be the preferred option for me.

**Comment by etobella** [comment]
Making the selection of procedure dependant to the exact name 'Procedure' is a bad option. We need to know. Using the category is not right. We need to find another option. I proposed two and Maxime this one. Which solution do you propose?

**Comment by pedrobaeza** [comment]
I think a field for determining the type of the document.page would be the best option. They don't need to be multi-valued to require m2m tags.

**Comment by etobella** [comment]
Well, the easiest one would be to use a field named `kind` or something like that.

Not too hard to implement.

**Comment by diggy128** [comment]
@etobella I think we need some more info to establish the use case.

Selecting the procedure category is not dependent on the name but rather on the reference name of the procedure.
If you mean the way to filter procedures in document.page view, a filter like:
`            <filter name="Procedures" domain="[('parent_id', 'child_of', ref('document_page_group_procedure'))]"/>` 
could be added to the search view without adding any more complexity to the data.

I stand by this because the procedure category will have to remain to have the template data for the procedure and adding an extra field could lead to inconsistencies (eg having a procedure with a different category/template than the designated one)

**Comment by etobella** [comment]
Procedure name is used here https://github.com/OCA/management-system/blob/16.0/mgmtsystem_nonconformity/views/mgmtsystem_nonconformity.xml#L292

This is obviously a problem. Also, category can be used to group your documents not by functionality but by theme. For example:

- Category: Human Resources
  - Document: Human resources procedure
  - Document: Work instruction to add a new employee
  - Document: Work instruction to manage leaves

Using categories will not work in this case. We need to classify them in another way in order to know if it is a work instruction, a procedure or something else...

**Comment by diggy128** [comment]
That should definitely be something like: 
`<field
      name="procedure_ids"
      attrs="{'readonly':[('state','not in',['draft','analysis'])]}"
      domain="['|', '|', ('parent_id','child_of', ref('document_page_group_procedure.document_page_group_procedure')),
('parent_id','child_of', ref('document_page_environmental_aspect.document_page_environmental_aspect)')),
('parent_id','child_of', ref('document_page_quality_manual.document_page_quality_manual')),
]"
  />`

Regarding the grouping, my opinion is that since the management modules deal with the functionality (procedures, work orders, manuals) that should be the default "basic" implementation.
Any further organization or segregation could be done with the _document_page_tag_ module.

I believe it makes more sense to have the documented information (aka procedures, work orders, manuals) as the root category. This way the documents can be controlled (aka submit change requests, review, approve) with more more fine-grained control top-down (e.g. a quality manager should be able to approve change requests for work orders from all departments).

In our case I added a few extra fields that provide granular control over who the document is used/applied from (which by the way replaced part of _Application Domain_ and _Responsibilities_:
![Screenshot_20230414_123852](https://user-images.githubusercontent.com/5067672/232008738-4bb69c8b-a178-42e2-a3bb-206b4df4437d.png)

The first field ('Τμήματα') is a many2many field that selects hr departments, the second ('Θέσεις εργασίας') selects hr.job and the third one ('Ετικέτες') hr.employee.tag.
Adding record rules using these fields makes the documents invisible for an employee that should not have access to a document, thus removing the need to control change request and any elevated rights.

++Using this approach it is very easy to select (or print out) the documents a new employee should use and apply during the on-boarding phase.

**Comment by etobella** [comment]
Well, right now categories can be used to filter using https://github.com/OCA/knowledge/tree/16.0/document_page_group with your approach I need to duplicate categories Manual / HR and Procedure / HR with the same configuration. 

I think it might be easier to add the field kind that allows us to filter them in a better way and use the current modules under OCA.

**Comment by diggy128** [comment]
> with your approach I need to duplicate categories Manual / HR and Procedure / HR with the same configuration

That's true, that is also the reason we decided to keep document category only as a document type reference and add the other fields mentioned above to separate them by function / position.

On a relevant note (and this has come up MANY times in Odoo customization), it seems easier to add a field to identity / separate a record as per the requirement when actually the data to make the separation is already there. The example with the fields I mentioned above is one great example where we wanted function separation by document and tried adding another field first, then using document_page_tag only to find out that both of these solutions required someone to check the documents at times to keep them up to date with their function (aka page tags with hr.jobs).
That's when it hit me that using the data that was already in Odoo (aka hr.department, hr.job and hr.employee.tag) made  completely sense and saved the overhead of having to synchronize different datasets (eg. hr.department named 'HR' and the document category 'HR'). 
**Furthermore using that approach creates a better data collection in Odoo where there are no hidden semantics eg. Whenever you mention 'HR department', it ALWAYS is an hr.department record pointing to id = 4 be it in hr.job or document.page or any other model.**
This can also provide useful data links that are not visible at first sight (the case I mentioned above of having all the documents a new employee will need during on-boarding).

**Comment by etobella** [comment]
Well, these problems might arise when people implement odoo in different places / companies.

I think your idea is great, and a module with this functionality will be welcome for sure. However, one thing doesn't solve the other one. The current approach is not sustainable. We need to find another way. I understand that using a tag might not be the best option. I will propose a field called kind in order to classify documents according to this, allowing us more flexibility. Using tag_ids might not be the best option (proposed on #519)

**Comment by max3903** [comment]
If a new field is added, would it be a m2o or a selection with a pre-defined list of values that would need to be discussed here?

@etobella Going back to your original requirement: 
> Right now, the only way to detect procedures is to use a single category created as data. It is a problem when the environment is complex, as a simple category for all your procedures might be hard to manage.

Could you be more specific and details something you cannot do today with the current features available? What do you mean by "hard to manage"?

**Comment by etobella** [comment]
I would opt for a selection field that will be increased in each module.

The complexity comes from using a single category. Categories are a tree of data, so, users try to split the content in this tree.

For example, in a hospital, I could classify information with something like **Surgery / Gynecology** and then add the specific content there. In this category I would add all documents related to Gynecology Surgeries: Procedures, Work Instructions and so on... Obviously, Surgery / Gynecology is not and hr.department and the same group might exist for each surgery specialty.

Right now, I need to add all data in the same category, and it can be horrible on a large company. Using the child might solve the problem, but it implies to duplicate the categories in different Parent categories.

**Comment by max3903** [comment]
@etobella Thanks for the explanation. Couple questions:

If you want to get all the content related to "Surgery / Gynecology", what do you want to do?

1. Go to Management Systems > Documentation > Surgery / Gynecology, and you get all the pages?
2. Go to Management Systems > Documentation > Content, filter with Surgery / Gynecology, and get all the pages?
3. Anything else?

Also, can the same page belong to multiple classifications, ie "Surgery / Gynecology" and "Radiology"?

Since page's category are also used to provide content template, I would like to keep them as is.

**Comment by diggy128** [comment]
> I think your idea is great, and a module with this functionality will be welcome for sure

I've been using this approach for two years. If you think it would be useful to the community I could push a PR to contribute it to the OCA (it lacks tests however).

Regarding the page category, I agree with @max3903 .

Since the Surgery / Gynecology case you mentioned is not an hr.department, I believe first you should look where (in the existing models) it could fit. I would guess it could be a location. That way you can have products, assets and HR assigned to each location / sublocation and even handle consuming materials (eg surgical knives in surgeries).

In the above case, expanding the fields I  mentioned in [https://github.com/OCA/management-system/issues/518#issuecomment-1508247012]  there could be a quaternary field that links documents to locations and sublocations. (As another example, I have used the location model in a set of in-house modules to handle allergen presence in each location according to the products it has or raw materials it consumes).

After 9 years customizing and expanding Odoo with modules, as I see it most data in Odoo are hierarchical trees and you can have multiple views depending on which branch you look from.
For example: 
When you want to look for Sale order lines (which belong to a sale order) you go from Sale order > sale order line
When you want information for a product you go to Inventory > Products. You don't go Sale order > sale order line > product (which although a valid path, it is not the easiest path to get the information).

I believe the same should be the case for Documents. 
When you want a Work instruction or a Procedure you go to Documents and search Top-Down.
When you want to search for a document that is used in Surgery / Gynecology again you should start the search from wherever Surgery / Gynecology is defined (in my example, a location) and then drill down.
That way you can have a Document that applies to many locations, many jobs and any combination you can imagine.

**Of course all hard-coded references to every document type mentioned in the management modules should be changed to its reference since that record itself is the document type defined in the management modules.**

**Comment by max3903** [comment]
@etobella As @diggy128 mentioned it, if "Surgery / Gynecology" is coming from an existing object in your instance, then create a module to add the relation, otherwise I would use tags to classify and filter.

**Comment by max3903** [comment]
@diggy128 If you want to publish your modules (document_page_hr_*), I would suggest to push them to OCA/knowledge.
